### ISSUE TITLE
Custom Scene Background (Image)

### ISSUE THREAD

**Issue by bcklup** [crsnbrt/keysim#52]
While designing my desk setup I've been looking through various mousepad designs that might fit my planned kb build.

Then I had the idea to open up photoshop and overlay the keysim export .png to images of my mousepad choices.

Just thought it would be very convenient if there was a similar feature in keysim where you can place a custom image as background (and even possibly control the scaling/placement?

I could even try contributing this feature myself if I find the time to study the project stack.

Any interest?

**Comment by crsnbrt** [comment]
nice idea, but I think it's a fairly niche feature that's probably not worth the added complexity and is already partially supported by the screenshot feature.
