### ISSUE TITLE
Feature Request: Add an option for clear cases on the website renderer

### ISSUE THREAD

**Issue by y4nrui** [crsnbrt/keysim#57]
Hi contributors, 

Love the online website renderer which makes it super easy to render keyboards! Just wanted to suggest a feature request to be able to render cases that are acrylic/polycarbonate. Thanks!

**Comment by crsnbrt** [comment]
I like the idea, but probably not going to add this since adding translucency would probably require rendering some internal faces of the case plus the pcb/plate/screws etc to look good.
