### ISSUE TITLE
Colorway filter does not reset

### ISSUE THREAD

**Issue by tofuBox** [crsnbrt/keysim#8]
The colorway filter does not reset after clicking on "X".

![image](https://user-images.githubusercontent.com/40531521/94395353-d718f980-01a2-11eb-9e28-478c3058b1f1.png)

Also is there a way for us to submit colorways to be added to the site? 
Overall awesome site to give a visualization on how certain sets would look on our keyboards.

**Comment by crsnbrt** [comment]
Thanks, I'll investigate this. 

As for the colorways, they can be submitted via pull request. For now, I want to keep the colorways in the community section to things that have been or will be physical products to avoid this list getting too long. I added the option to generate a permalink if, for example, you wanted to share a design for an interest check. 

But I'm open to feedback here if there is a desire for some kind of "gallery" feature.
