### ISSUE TITLE
what are the requirements to run this project?

### ISSUE THREAD

**Issue by burntato** [crsnbrt/keysim#81]
I have a project in mind that can use this keyboard simulator but it seems that every time I tried to install it gives me an error, and that got me thinking.

what are the requirements for this project (such as node ver, etc) I tried so hard to run this project after cloning it with no luck

**Comment by ulysses-ck** [comment]
HI @burntato , did you already managed to get it work?

**Comment by burntato** [comment]
> HI @burntato , did you already managed to get it work?

yes i did ended up making it work, it requires installing all the requirements after cloning the projects, some of the dependencies requires manual install though because it uses the old version

**Comment by ulysses-ck** [comment]
> > HI @burntato , did you already managed to get it work?
> 
> yes i did ended up making it work, it requires installing all the requirements after cloning the projects, some of the dependencies requires manual install though because it uses the old version

Thanks. I really appreciate that you take the time to reply. I'm gonna look to get it working too. I already installed the cairo and gtk to use node-canvas but this is very annoying.
